export const REGION_RECOMMENDATIONS: Record<string, string[]> = {
  "Analanjirofo": ["Vary", "Mangahazo", "Tsaramaso"],
  "Diana": ["Vary", "Katsaka", "Mangahazo", "Voanjo"],
  "Alaotra-Mangoro": ["Vary", "Katsaka", "Tsaramaso", "Voatabia"],
  "Analamanga": ["Vary", "Ovy", "Tongolo", "Voatabia", "Karoty", "Tsaramaso"],
  "Androy": ["Mangahazo", "Vomanga", "Voanjo"],
  "Anosy": ["Vary", "Mangahazo", "Vomanga", "Katsaka"],
  "Ihorombe": ["Katsaka", "Voanjo", "Mangahazo"],
  "Atsimo-Andrefana": ["Voanjo", "Mangahazo", "Katsaka"],
  "Amoron'i Mania": ["Vary", "Ovy", "Tsaramaso", "Tongolo", "Karoty"],
  "Atsimo-Atsinanana": ["Vary", "Mangahazo"],
  "Atsinanana": ["Vary", "Mangahazo"],
  "Betsiboka": ["Vary", "Katsaka", "Voanjo", "Tsaramaso"],
  "Bongolava": ["Katsaka", "Voanjo", "Mangahazo", "Vary"],
  "Haute Matsiatra": ["Vary", "Ovy", "Tsaramaso", "Tongolo", "Voatabia"],
  "Itasy": ["Vary", "Katsaka", "Voatabia", "Tongolo", "Tsaramaso"],
  "Boeny": ["Vary", "Katsaka", "Voanjo", "Mangahazo"],
  "Melaky": ["Vary", "Katsaka", "Voanjo"],
  "Menabe": ["Voanjo", "Katsaka", "Mangahazo"],
  "Sava": ["Vary", "Mangahazo", "Katsaka"],
  "Sofia": ["Vary", "Voanjo", "Katsaka", "Mangahazo"],
  "Vakinankaratra": ["Vary", "Ovy", "Tongolo", "Karoty", "Voatabia", "Tsaramaso"],
  "Vatovavy-Fitovinany": ["Vary", "Mangahazo"]
};
